on:
  pull_request: # Se dispara al abrir o actualizar una PR
    branches: [ main ]

jobs:
  data_quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
              
      # -------------------------------------------------------------
      # PASO CLAVE: Ejecutar la prueba de calidad de datos
      # -------------------------------------------------------------
      - name: Verificar el Conteo de Registros
        # El código 0 será éxito; cualquier otro código causará el fallo del workflow
        run: python C:/jmalo/FUENTES/GITHUB/fuentes/desa/proceso_calidad/proceso_calidad.py
