name: Auto Commit y Push a Develop

on:
  # Dispara este workflow manualmente para evitar loops
  workflow_dispatch:

jobs:
  auto_git_actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Configurar Identidad Genérica del Bot 🤖
        # Esto es estándar y funcional para CUALQUIER usuario que inicie la pipeline
        run: |
          git config user.name "jmalomolina@gmail.com"
          git config user.email "jmalomolina-source"
          ssh-keygen -t ed25519 -C "jmalomolina@gmail.com"

      - name: 2. Checkout del repositorio
        uses: actions/checkout@v4
        # IMPORTANTE: Fetchear la historia completa para que el commit no falle
        with:
          fetch-depth: 0 
          # La acción de commit necesita un token de escritura, lo toma de esta forma:
          token: ${{ secrets.GITHUB_TOKEN }} 
      
          
      # -----------------------------------------------------------------
      # EJECUTAR COMANDOS - Simulando tus comandos
      # -----------------------------------------------------------------
            
      - name: Git Add, Commit y Push
        # Nota: La acción checkout@v4 ya soporta el token para el push
        run: |
          # El comando 'git add .'
          git add .
          
          # El comando 'git commit -m "..."'
          git commit -m "🤖 Actualización automática de log después del CI"
          
          # El comando 'git push -u origin develop' (si estás en la rama develop)
          # Asume que el workflow se disparó desde develop
          git push origin develop